name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.0

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Install Hugo
      run: |
        CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
        hugo version
